language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - python setup.py develop
  - easy_install pyramid_jinja2[testing]
  - pip install nosexcover
script:
  - mkdir -p shippable/testresults
  - nosetests --with-xunit --xunit-file=$(pwd)/shippable/testresults/nosetests.xml --with-xcoverage --cover-package=pyramid_jinj2 --xcoverage-file=$(pwd)/shippable/codecoverage/coverage.xml
